spring:
  application:
    name: spider-nest
zookeeper:
  retryTimes: 10
  retryInterval: 5000
policy:
  taskPolicy: noAction
  serverShutDownPolicy: cleanTask
#logging:
#  path: /home/ds02/bigdataplatform/logs

